### ISSUE TITLE
Create zarf package to modify storage classes after init

### ISSUE THREAD

**Issue by zack-is-cool** [defenseunicorns/narwhal-delivery-zarf-package-eks-addons#19]
```[tasklist]
### Tasks
- [ ] Add gp3 storage class
- [ ] Add EFS storage class
- [ ] Remove the default setting from gp2 storage class that's installed via the ebs-csi-driver marketplace addon
```

**Comment by zack-is-cool** [comment]
Completed via https://github.com/defenseunicorns/narwhal-delivery-zarf-package-eks-addons/tree/main/packages/storageclass
