### ISSUE TITLE
Create package for AWS secrets store csi driver

### ISSUE THREAD

**Issue by zack-is-cool** [defenseunicorns/narwhal-delivery-zarf-package-eks-addons#21]
```[tasklist]
### Tasks
- [ ] Create zarf package for [aws secrets store csi driver](https://github.com/aws/secrets-store-csi-driver-provider-aws)
- [ ] Check for iron bank availability
- [ ] Create UDS task runner jobs for building + publishing
- [ ] Integrate into UDS bundle
```
